### ISSUE TITLE
请问后续有无支持其他vtuber的计划?

### ISSUE THREAD

**Issue by nyaang** [1996scarlet/OpenVtuber#1]
如题，repo的名称是OpenVtuber，但现在README里只看到Kizuna AI的demo.

以后会不会加上其他的vtuber，比如月の美兎，猫宮ひなた，湊あくあ？主要问题是不是开源3D模型的来源或渠道？

<del>好吧，上面的内容都不是重点。</del>我只是想夸夸开发者，拿一套SOTA的方法来做这种东西真的是鬼才。第一次看到拿retinaface来干这个的。

**Comment by 1996scarlet** [comment]
![dd](https://user-images.githubusercontent.com/22913521/69607156-98388580-105f-11ea-95c6-f683f0909f5e.gif)

你可以在[NICONICO-schwarz](https://3d.nicovideo.jp/users/196981)找到更多的模型

甚至可以用**博丽灵梦** (臭DD爬)

**Comment by nyaang** [comment]
草，我想起来逸站上还真有用[博丽灵梦](https://space.bilibili.com/297340/)来Vtuber出道的
