### ISSUE TITLE
Commercial license 

### ISSUE THREAD

**Issue by johndpope** [1996scarlet/OpenVtuber#14]
Is it possible to license code commercially? Code is GPL which strictly prohibits sub licensing.

**Comment by 1996scarlet** [comment]
The Face Detection, Face Alignment, and Iris Localization model are following MIT and Apache 2.0 License.
However, for head posture estimation, the adopted AIFI Anthropometric Model is strictly prohibited for commercial use.

While not recommended, you can replace the head pose estimation method to get rid of the restrictions of GPL V3.

**Comment by johndpope** [comment]
cool. thanks
