### ISSUE TITLE
请问可以离线测试吗？

### ISSUE THREAD

**Issue by DWCTOD** [1996scarlet/OpenVtuber#18]
您好，感谢大佬的分享
运行到这里的时候出现问题
cd NodeServer && yarn # install node modules
是不是不能离线（断网）测试

**Comment by 1996scarlet** [comment]
首次运行时需要使用 yarn 安装依赖（需要联网），之后就不需要联网运行了

你也可以查看 [NodeServer/yarn.lock](https://github.com/1996scarlet/OpenVtuber/blob/970229d3a5ebe14a7519352da039d00a0b87e2d9/NodeServer/yarn.lock) 中需要的软件包，手动在其他机器下载后安装到离线机器中

**Comment by DWCTOD** [comment]
谢谢大佬
还有一个问题想请教一下，该项目生成的结果是如何保存的 （本地运行有点卡，想保存下来对比一下效果）
