### ISSUE TITLE
socketio.exceptions.ConnectionError: OPEN packet not returned by server

### ISSUE THREAD

**Issue by Cip0** [1996scarlet/OpenVtuber#3]
Running the python client gives me this error. The server is running. Any hint on how to fix this?

> Traceback (most recent call last):
>   File ".\vtuber_link_start.py", line 46, in <module>
>     sio.connect("http://127.0.0.1:6789")
>   File "C:\Users\cipol\Projects\Avatar\Engagement research\OpenVtuber\venv\lib\site-packages\socketio\client.py", line 282, in connect
>     six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
>   File "<string>", line 3, in raise_from
> socketio.exceptions.ConnectionError: OPEN packet not returned by server

**Comment by 1996scarlet** [comment]
I have not come across this problem.
We strongly recommend that you test this project in an Ubuntu environment.

**Comment by rkuo2000** [comment]
same error (OPEN packet not return by server) in both Windows & MAC OS
NodeServer  : socket.io@2.3.0
PythonClient : python-socketio==4.6.0

**Comment by rkuo2000** [comment]
I found the fix (for using python-socketio==4.6.0)
pip3 install python-engineio==3.13.0

**Comment by 1996scarlet** [comment]
> I found the fix (for using python-socketio==4.6.0)
> pip3 install python-engineio==3.13.0

Thank you for your help !!!
I'll add this in the requirements.txt
