### ISSUE TITLE
How to hook up to laptop's webcam?

### ISSUE THREAD

**Issue by dawnFirefly** [1996scarlet/OpenVtuber#4]
Awesome work, but I have few question: 

1.How to hook up to laptop's webcam? in readme it said "python3 vtuber_link_start.py <your-video-path>". I am able to test it on a .mp4 video, how to make the program read live video from webcam?

2. I am only able to get ~14 fps output with my laptop's i5-1035G7 & iGPU in windows 10, is this possible to get better result?

**Comment by 1996scarlet** [comment]
1. Try `python3 vtuber_link_start.py <your-cam-id>` eg. `python3 vtuber_link_start.py /dev/video0`.
2. The MMD rander of ThreeJS may cost much, enable browser hardware acceleration (tested on chrome) for better result.
