### ISSUE TITLE
你们是怎么利用得到的角度信息，去控制相应的动画人物的？

### ISSUE THREAD

**Issue by shoutOutYangJie** [1996scarlet/OpenVtuber#5]
还有，我查了一下MMD是制作3d动画的程序。你们用角度信息等控制人物，具体的实现是在这个仓库中吗？小白想学习一下。谢谢

**Comment by 1996scarlet** [comment]
`kizuna.html`文件中给出了mmd模型驱动接口的调用示例

角度信息驱动模型的流程：
* Python脚本计算出欧拉角
* 通过socketio上传给nodejs
* nodejs通过socketio将欧拉角分发给webpage
* webpage中调用驱动接口控制模型

**Comment by shoutOutYangJie** [comment]
ok，看来实现起来挺费力气。还是闭源的





------------------ 原始邮件 ------------------
发件人: Remilia Scarlet <notifications@github.com&gt;
发送时间: 2021年1月5日 21:32
收件人: 1996scarlet/OpenVtuber <OpenVtuber@noreply.github.com&gt;
抄送: shoutOutYangJie <312358434@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[1996scarlet/OpenVtuber] 你们是怎么利用得到的角度信息，去控制相应的动画人物的？ (#5)





 
kizuna.html文件中给出了mmd模型驱动接口的调用示例
 
角度信息驱动模型的流程：
  
Python脚本计算出欧拉角 

通过socketio上传给nodejs 

nodejs通过socketio将欧拉角分发给webpage 

webpage中调用驱动接口控制模型
