### ISSUE TITLE
Facial Landmarks are shivering continuously, Is there any way to stabilize them as they are affecting output on 3d character as well??

### ISSUE THREAD

**Issue by MuhamadAlee** [1996scarlet/OpenVtuber#7]

**Comment by 1996scarlet** [comment]
Please refer to our new work for stable facial landmarks.
[A Backbone Replaceable Fine-tuning Framework for Stable Face Alignment](https://arxiv.org/abs/2010.09501v2)
The code shall be released soon.

**Comment by keetsky** [comment]
Tell me when you release it.

**Comment by mariolew** [comment]
Not easy to reproduce the results of [A Backbone Replaceable Fine-tuning Framework for Stable Face Alignment](https://arxiv.org/abs/2010.09501v2) @1996scarlet

**Comment by EEWenbinWu** [comment]
just release the implementation of jitter loss might be enough
