### ISSUE TITLE
关于gaze预测

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [1996scarlet/OpenVtuber#8]
很棒的工作！

我看到gaze的预测是用2d关键点算出来的，通过calculate_3d_gaze这个函数，可以给出原理的相关介绍吗，或者推导的链接~

谢谢！

**Comment by 1996scarlet** [comment]
主要参考了组里的两篇工作：
* [Siggraph 2016][Realtime 3D Eye Gaze Animation Using a Single RGB Camera](http://humanmotion.ict.ac.cn/papers/2016P1_EyeGaze/details.htm)
* [TVCG 2021][Realtime and Accurate 3D Eye Gaze Capture with DCNN-based Iris and Pupil Segmentation](http://humanmotion.ict.ac.cn/papers/2019P4_EYE/paper.pdf)

如果你对人脸图形学研究感兴趣，或者有任何学术问题，可以联系[夏老师](http://sourcedb.ict.cas.cn/cn/jssrck/200909/t20090917_2496743.html)
